# questions.py
# Stores all quiz questions for different categories

questions = [
    # ===== HEART =====
    ("heart", "How many chambers does the human heart have?", "2", "4", "4"),
    ("heart", "Which side of the heart pumps blood to the lungs?", "Right", "Left", "Right"),
    ("heart", "What is the normal resting heart rate range for adults?", "60-100 bpm", "120-160 bpm", "60-100 bpm"),
    ("heart", "Which blood vessels carry blood away from the heart?", "Arteries", "Veins", "Arteries"),
    ("heart", "Which blood vessels return blood to the heart?", "Veins", "Arteries", "Veins"),
    ("heart", "What is the largest artery in the body?", "Aorta", "Pulmonary Artery", "Aorta"),
    ("heart", "Which part of the heart receives oxygen-rich blood from the lungs?", "Left Atrium", "Right Atrium", "Left Atrium"),
    ("heart", "What separates the left and right sides of the heart?", "Septum", "Valve", "Septum"),
    ("heart", "Which chamber of the heart pumps oxygenated blood to the body?", "Left Ventricle", "Right Ventricle", "Left Ventricle"),
    ("heart", "Which type of blood is carried by the pulmonary veins?", "Oxygenated", "Deoxygenated", "Oxygenated"),
    ("heart", "Which part of the heart receives oxygen-rich blood from the lungs?", "Left atrium", "Right atrium", "Left atrium"),
("heart", "How many valves are there in the human heart?", "4", "3", "4"),
("heart", "Which valve is located between the left atrium and left ventricle?", "Mitral valve", "Tricuspid valve", "Mitral valve"),
("heart", "Which chamber of the heart pumps blood to the lungs?", "Right ventricle", "Left ventricle", "Right ventricle"),
("heart", "What is the main artery that carries blood from the heart to the body?", "Aorta", "Pulmonary artery", "Aorta"),
("heart", "Which side of the heart deals with oxygenated blood?", "Left side", "Right side", "Left side"),
("heart", "What is the natural pacemaker of the heart called?", "SA node", "AV node", "SA node"),
("heart", "Which chamber of the heart has the thickest walls?", "Left ventricle", "Right ventricle", "Left ventricle"),
("heart", "Which blood vessels carry blood toward the heart?", "Veins", "Arteries", "Veins"),
("heart", "Which part of the heart receives deoxygenated blood from the body?", "Right atrium", "Left atrium", "Right atrium"),
("heart", "How many chambers are there in the human heart?", "4", "2", "4"),
("heart", "Which blood vessels carry blood away from the heart?", "Arteries", "Veins", "Arteries"),
("heart", "What type of muscle is the heart made of?", "Cardiac muscle", "Skeletal muscle", "Cardiac muscle"),
("heart", "Which side of the heart pumps blood to the lungs?", "Right side", "Left side", "Right side"),
("heart", "Which part of the heart separates the left and right sides?", "Septum", "Valve", "Septum"),
("heart", "What is the function of heart valves?", "Prevent backflow of blood", "Pump blood", "Prevent backflow of blood"),
("heart", "Which blood vessels bring oxygen-rich blood to the heart?", "Pulmonary veins", "Pulmonary arteries", "Pulmonary veins"),
("heart", "What does the heart pump through the body?", "Blood", "Oxygen only", "Blood"),
("heart", "How many times does an average heart beat per minute?", "About 72", "About 20", "About 72"),
("heart", "What is the largest vein in the human body?", "Vena cava", "Aorta", "Vena cava"),



    # ===== LUNGS =====
    ("lungs", "How many lungs does a human have?", "1", "2", "2"),
    ("lungs", "Which gas do lungs absorb from the air?", "Oxygen", "Carbon Dioxide", "Oxygen"),
    ("lungs", "Which gas do humans exhale the most?", "Oxygen", "Carbon Dioxide", "Carbon Dioxide"),
    ("lungs", "What protects the lungs?", "Rib cage", "Skull", "Rib cage"),
    ("lungs", "What is the main muscle used for breathing?", "Diaphragm", "Trachea", "Diaphragm"),
    ("lungs", "What is the name of the air sacs in the lungs?", "Alveoli", "Bronchi", "Alveoli"),
    ("lungs", "What is the primary function of the lungs?", "Gas exchange", "Digestion", "Gas exchange"),
    ("lungs", "What is the tube that carries air to the lungs?", "Trachea", "Esophagus", "Trachea"),
    ("lungs", "What is the name of the membrane surrounding the lungs?", "Pleura", "Pericardium", "Pleura"),
    ("lungs", "What is the process of breathing in called?", "Inhalation", "Exhalation", "Inhalation"),
    ("lungs", "What is the process of breathing out called?", "Exhalation", "Inhalation", "Exhalation"),
    ("lungs", "What is the name of the largest part of the lungs?", "Lobe", "Alveolus", "Lobe"),
    ("lungs", "What is the name of the smallest air passages in the lungs?", "Bronchioles", "Bronchi", "Bronchioles"),
    ("lungs", "What is the name of the flap that covers the trachea during swallowing?", "Epiglottis", "Uvula", "Epiglottis"),
    ("lungs", "What is the name of the condition where the air sacs in the lungs become inflamed?", "Pneumonia", "Asthma", "Pneumonia"),
    ("lungs", "Which organ works with the lungs to circulate oxygen?", "Heart", "Stomach", "Heart"),
("lungs", "What is the normal breathing rate for a healthy adult per minute?", "12-20 breaths", "30-40 breaths", "12-20 breaths"),
("lungs", "Which side of the body has three lung lobes?", "Right side", "Left side", "Right side"),
("lungs", "Which gas is produced by cells and carried to the lungs for exhalation?", "Carbon Dioxide", "Oxygen", "Carbon Dioxide"),
("lungs", "What is the medical term for difficulty breathing?", "Dyspnea", "Apnea", "Dyspnea"),
("lungs", "Which part of the lung contains the alveoli?", "Bronchioles", "Trachea", "Bronchioles"),
("lungs", "Which structure divides the right and left lungs?", "Mediastinum", "Pleura", "Mediastinum"),
("lungs", "What is the main passage between the mouth/nose and the lungs?", "Trachea", "Pharynx", "Trachea"),
("lungs", "What happens to the diaphragm during inhalation?", "Contracts and moves down", "Relaxes and moves up", "Contracts and moves down"),
("lungs", "What is the name for inflammation of the bronchial tubes?", "Bronchitis", "Pneumonia", "Bronchitis"),
("lungs", "Which organ works closely with the lungs to pump oxygenated blood?", "Heart", "Liver", "Heart"),
("lungs", "Which part of the respiratory system connects the throat to the lungs?", "Trachea", "Bronchioles", "Trachea"),
("lungs", "Which gas do plants release that humans need for breathing?", "Oxygen", "Nitrogen", "Oxygen"),
("lungs", "Which condition makes it hard to breathe due to narrowed airways?", "Asthma", "Pneumonia", "Asthma"),
("lungs", "What are the two main branches of the trachea called?", "Bronchi", "Alveoli", "Bronchi"),
("lungs", "Which structure in the lungs exchanges gases with blood?", "Alveoli", "Bronchi", "Alveoli"),
("lungs", "Which activity makes lungs work harder?", "Running", "Sleeping", "Running"),
("lungs", "Which muscle separates the lungs from the stomach area?", "Diaphragm", "Esophagus", "Diaphragm"),
("lungs", "What is the medical term for windpipe?", "Trachea", "Bronchioles", "Trachea"),
("lungs", "What is the main function of bronchioles?", "Carry air to alveoli", "Store oxygen", "Carry air to alveoli"),


    # ===== DENTAL =====
    ("dental", "How many permanent teeth does an adult human have?", "32", "28", "32"),
    ("dental", "Which type of teeth are used for cutting food?", "Incisors", "Molars", "Incisors"),
    ("dental", "Which type of teeth are used for grinding food?", "Molars", "Canines", "Molars"),
    ("dental", "What covers and protects the teeth?", "Enamel", "Dentin", "Enamel"),
    ("dental", "Which teeth are sharp and used for tearing food?", "Canines", "Molars", "Canines"),
    ("dental", "What is the hardest substance in the human body?", "Enamel", "Dentin", "Enamel"),
("dental", "Which type of teeth are used for cutting food?", "Incisors", "Molars", "Incisors"),
("dental", "How many permanent teeth does an adult have?", "32", "28", "32"),
("dental", "Which mineral is essential for strong teeth?", "Calcium", "Iron", "Calcium"),
("dental", "What is the main cause of tooth decay?", "Bacteria", "Virus", "Bacteria"),
("dental", "Which teeth are the sharpest for tearing food?", "Canines", "Premolars", "Canines"),
("dental", "What is the thin layer covering the crown of a tooth?", "Enamel", "Cementum", "Enamel"),
("dental", "Which part of the tooth contains nerves and blood vessels?", "Pulp", "Dentin", "Pulp"),
("dental", "What is dental plaque mostly made of?", "Bacteria", "Saliva", "Bacteria"),
("dental", "Which vitamin is important for healthy gums?", "Vitamin C", "Vitamin D", "Vitamin C"),
("dental", "Which teeth are the largest in the mouth?", "Molars", "Canines", "Molars"),
("dental", "Which dental tool is used to check cavities?", "Explorer", "Scalpel", "Explorer"),
("dental", "What do dentists use to numb a tooth before treatment?", "Local anaesthesia", "General anaesthesia", "Local anaesthesia"),
("dental", "What is the pink tissue that supports the teeth?", "Gums", "Tongue", "Gums"),
("dental", "Which type of tooth is replaced around age 6-7 years?", "Primary teeth", "Permanent teeth", "Primary teeth"),
("dental", "What is the main function of molars?", "Grinding food", "Cutting food", "Grinding food"),
("dental", "Which part of the tooth is visible above the gum line?", "Crown", "Root", "Crown"),
("dental", "Which device helps straighten teeth?", "Braces", "Denture", "Braces"),
("dental", "What is the sticky film that forms on teeth after eating?", "Plaque", "Tartar", "Plaque"),
("dental", "What is the scientific term for baby teeth?", "Deciduous teeth", "Wisdom teeth", "Deciduous teeth"),
    ("dental", "What is the main purpose of flossing?", "Remove plaque between teeth", "Whiten teeth", "Remove plaque between teeth"),
    ("dental", "What is the term for the procedure to remove a tooth?", "Extraction", "Filling", "Extraction"),
    ("dental", "What is the name of the dental specialist who performs root canals?", "Endodontist", "Orthodontist", "Endodontist"),
    ("dental", "What is the term for the hard tissue under the enamel?", "Dentin", "Cementum", "Dentin"),
    ("dental", "What is the purpose of dental sealants?", "Prevent cavities", "Whiten teeth", "Prevent cavities"),
    ("dental", "What is the term for wisdom teeth that do not have enough space to emerge?", "Impacted wisdom teeth", "Erupted wisdom teeth", "Impacted wisdom teeth"),
    ("dental", "What is the name of the dental tool used to clean teeth?", "Scaler", "Mirror", "Scaler"),
    ("dental", "What is the term for inflammation of the gums?", "Gingivitis", "Periodontitis", "Gingivitis"),
    ("dental", "Which type of toothpaste helps prevent cavities?", "Fluoride toothpaste", "Whitening toothpaste", "Fluoride toothpaste"),


    # ===== BRAIN =====
    ("brain", "Which part of the brain controls balance?", "Cerebellum", "Medulla", "Cerebellum"),
    ("brain", "What is the average weight of the human brain?", "1.4 kg", "800 g", "1.4 kg"),
    ("brain", "Which part of the brain controls breathing and heartbeat?", "Medulla", "Cerebrum", "Medulla"),
    ("brain", "Which part of the brain is responsible for thinking and memory?", "Cerebrum", "Cerebellum", "Cerebrum"),
    ("brain", "Which part of the brain connects to the spinal cord?", "Brainstem", "Thalamus", "Brainstem")
    ("brain", "Which part of the brain controls balance and coordination?", "Cerebellum", "Medulla", "Cerebellum"),
("brain", "Which part of the brain controls breathing and heartbeat?", "Medulla", "Cerebrum", "Medulla"),
("brain", "Which part of the brain is responsible for thinking and memory?", "Cerebrum", "Cerebellum", "Cerebrum"),
("brain", "What protects the brain inside the skull?", "Cerebrospinal fluid", "Blood plasma", "Cerebrospinal fluid"),
("brain", "Which is the largest part of the human brain?", "Cerebrum", "Cerebellum", "Cerebrum"),
("brain", "Which part of the brain controls voluntary movements?", "Cerebrum", "Medulla", "Cerebrum"),
("brain", "Which part of the brain controls involuntary actions like digestion?", "Medulla", "Cerebellum", "Medulla"),
("brain", "What connects the brain to the spinal cord?", "Medulla oblongata", "Cerebrum", "Medulla oblongata"),
("brain", "Which part of the brain is involved in balance when riding a bicycle?", "Cerebellum", "Medulla", "Cerebellum"),
("brain", "Which part of the brain controls vision?", "Occipital lobe", "Frontal lobe", "Occipital lobe"),
("brain", "Which part of the brain processes sound?", "Temporal lobe", "Parietal lobe", "Temporal lobe"),
("brain", "Which part of the brain helps us sense touch and temperature?", "Parietal lobe", "Occipital lobe", "Parietal lobe"),
("brain", "What is the brain made up of?", "Nerve cells", "Muscle cells", "Nerve cells"),
("brain", "Which is the fastest communication pathway in the body?", "Nervous system", "Circulatory system", "Nervous system"),
("brain", "Which part of the brain helps in learning and reasoning?", "Cerebrum", "Medulla", "Cerebrum"),
("brain", "Which part of the brain helps you stay awake and alert?", "Reticular formation", "Cerebellum", "Reticular formation"),
("brain", "Which part of the brain regulates emotions?", "Limbic system", "Occipital lobe", "Limbic system"),
("brain", "Which part of the brain stores long-term memories?", "Hippocampus", "Cerebellum", "Hippocampus"),
("brain", "Which part of the brain controls speech?", "Broca's area", "Wernicke's area", "Broca's area"),
("brain", "Which side of the brain controls the right side of the body?", "Left hemisphere", "Right hemisphere", "Left hemisphere"),
    ("brain", "Which part of the brain is responsible for processing emotions?", "Limbic system", "Cerebellum", "Limbic system"),
    ("brain", "What is the outer layer of the brain called?", "Cerebral cortex", "Medulla", "Cerebral cortex"),
    ("brain", "Which part of the brain helps in regulating sleep?", "Hypothalamus", "Thalamus", "Hypothalamus"),
    ("brain", "What is the main function of the thalamus?", "Relay sensory information", "Control balance", "Relay sensory information"),
    ("brain", "Which part of the brain is involved in decision-making?", "Prefrontal cortex", "Occipital lobe", "Prefrontal cortex"),
]
